apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: daily-integration-test
spec:
  schedule: "0 0 * * *"
  concurrencyPolicy: "Replace"
  startingDeadlineSeconds: 0
  workflowSpec:
     entrypoint: main-tpl
     arguments:
       parameters:
       - name: repo
         value: https://gitlab.com/lopment/travel.git
       - name: revision
         value: release/0.0.1
     templates:
     - name: main-tpl
       dag:
         tasks:
         - name: call-checkout
           template: checkout-tpl
         - name: call-build
           template: build-tpl
           depends: "call-checkout.Succeeded"
           arguments:
             artifacts:
             - name: src-art
               from: "{{tasks.call-checkout.outputs.artifacts.src-art}}" 
         - name: call-integration-test
           template: integration-test-tpl
           arguments:
   
             artifacts:
             - name: src-art
               from: "{{tasks.call-checkout.outputs.artifacts.src-art}}"
           depends: "call-build.Succeeded"
         - name: call-cov-test
           template: cov-test-tpl
           depends: "call-build.Succeeded"
           arguments:
             artifacts:
             - name: src-art
               from: "{{tasks.call-checkout.outputs.artifacts.src-art}}"
         - name: call-report
           template: report-tpl
           depends: "call-cov-test.Succeeded"
     - name: checkout-tpl
       script:
         image: alpine:3.14
         command: ["sh","-c"]
         args: ["ls /src "]
       inputs:
         artifacts:
         - name: src-art
           path: /src
           git:
             repo: "{{workflow.parameters.repo}}"
             revision: "{{workflow.parameters.revision}}" 
       outputs:
         artifacts:
         - name: src-art
           path: /src
     - name: build-tpl
       container:
         image: maven:3.3-jdk-8
         command: ["sh", "-c"]
         args: [" ls /src &&  cd /src/backend && mvn package -DskipTests"]
       inputs:
         artifacts:
         - name: src-art
           path: /src
       outputs:
         artifacts:
         - name: bin-art
           path: /src
     - name: integration-test-tpl
       container:
         image:  maven:3.3-jdk-8
         command: ["sh","-c"]
         args: ["ls /src && cd /src/backend && mvn verify -Pfailsafe"]
       inputs:
         artifacts:
         - name: src-art
           path: /src
     - name: cov-test-tpl
       container:
         image: maven:3.3-jdk-8
         command: ["sh","-c"]
         args: ["ls /src && cd /src/backend && mvn prepare-package"]
       inputs:
         artifacts:
         - name: src-art
           path: /src
       outputs:
         artifacts:
         - name: cov-art
           path: /src
     - name: report-tpl
       container:
         image: alpine:3.14
         command: ["echo"]
         args: ["reports status"]
