apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: docker-workflow-template
spec:
  templates:
  - name: publish-tpl
    script:
      image: docker:19.03.13
      command: [sh, -c]
      args: ["until docker ps; do sleep 3; done; cd {{inputs.parameters.src_path}}; docker build -t {{inputs.parameters.image}} .; docker login {{inputs.parameters.image_registry}} -u tonidev85@gmail.com -p 1985nicolas5891; docker push {{inputs.parameters.image}}"]
      env:
      - name: DOCKER_HOST               # the docker daemon can be access on the standard port on localhost
        value: 127.0.0.1
    sidecars:
    - name: dind
      image: docker:19.03.13-dind          # Docker already provides an image for running a Docker daemon
      command: [dockerd-entrypoint.sh]
      env:
      - name: DOCKER_TLS_CERTDIR         # Docker TLS env config
        value: ""
      securityContext:
        privileged: true                # the Docker daemon can only run in a privileged container
        # mirrorVolumeMounts will mount the same volumes specified in the main container
        # to the sidecar (including artifacts), at the same mountPaths. This enables
        # dind daemon to (partially) see the same filesystem as the main container in
        # order to use features such as docker volume binding.
      mirrorVolumeMounts: true
    inputs:
      parameters:
      - name: image_registry
      - name: image
      - name: src_path
      artifacts:
      - name: bin-art
        path: /src